spring:
  application:
    name: delivery-services
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cassandra:
    host: cassandra
    port: 9042
  redis:
    host: redis
    port: 6379

