version: '2'
services:
  delivery-services:
    build: .
    links:
      - rabbitmq
      - mongodb
      - redis
    depends_on:
      - rabbitmq
      - mongodb
      - redis

  mongodb:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  rabbitmq:
    hostname: rabbitmq-dublin
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    hostname: redis-montreal
    image: redis
    ports:
      - "6379:6379"
