version: '2'
services:
  delivery-services:
    build: .
    links:
      - rabbitmq
      - cassandra
      - redis
    depends_on:
      - rabbitmq
      - cassandra
      - redis

  cassandra:
    hostname: cassandra-adelaide
    image: spotify/cassandra
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 9042
    ports:
      - "9042:9042"

  rabbitmq:
    hostname: rabbitmq-dublin
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    hostname: redis-montreal
    image: redis
    ports:
      - "6379:6379"
