cassandra:
  hostname: cassandra-adelaide
  image: cassandra:latest
  command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
  expose:
    - 7000
    - 7001
    - 7199
    - 9042
    - 9160

rabbitmq:
  hostname: rabbitmq-dublin
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"

redis:
  hostname: redis-montreal
  image: redis
  ports:
    - "6379:6379"
