spring:
  application:
    name: delivery
  data:
    mongodb:
      host: localhost
      database: delivery-db
delivery:
    service:
        queue: 
            cache: delivery-service-cache
            persist: delivery-service-persist
        exchange: delivery-service-exchange
server:
    contextPath: /api
