spring:
  application:
    name: delivery
  data:
    mongodb:
      host: localhost
      database: delivery-db
delivery:
    service:
        queue: delivery-service
        exchange: delivery-service-exchange
server:
    contextPath: /api
